"use client"
import Head from 'next/head'
import NavBar from '../components/NavBar'
import LoginForm from '../components/LoginForm'
import { Inter } from 'next/font/google'
// import styles from '../styles/Login.module.css'  
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation';
import axios from 'axios'

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })


export default function Users() {
    const { push } = useRouter();

    useEffect( ()=>{
        // run once
    }, [])

  return (
    <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
      <NavBar></NavBar>
        <div>Users</div>
      </main>
    </>
  )
}
